project:
  type: website
  output-dir: docs

website:
  title: "F.J. Martinez-Murcia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - publications.qmd
      - teaching.qmd
      - communication.qmd
      - blog.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

